version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
     - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  mongo:
    container_name: mongo
    image: mongo:6.0.4-jammy
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGODB_DB_PORT}:${MONGODB_DB_PORT}
    restart: always

  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - ${REDIS_DB_PORT}:${REDIS_DB_PORT}
    restart: always

volumes:
  postgres-data:
  mongo-data: